# Generated by Django 3.2.9 on 2021-11-23 10:09

from django.db import migrations, models
import student_management_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_leavereportstudent_subject_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImageStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('images', models.FileField(upload_to=student_management_app.models.get_upload_path)),
            ],
        ),
    ]
