# Generated by Django 3.2.9 on 2021-11-27 10:19

from django.db import migrations, models
import student_management_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_postimagestudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(upload_to=student_management_app.models.upload_profile_pic),
        ),
    ]
